// Run against isolated Next and FastAPI test databases, never production.
import test from 'node:test';
import assert from 'node:assert/strict';
const base = process.env.AURA_TEST_URL || 'http://127.0.0.1:3100';
test('Next session-to-FastAPI bridge authenticates, validates, and preserves account boundaries', async () => {
  const post = (path, data, cookie) => fetch(`${base}/api/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, body: JSON.stringify(data) });
  assert.equal((await post('voice/challenge', { purpose: 'enroll' })).status, 401);
  const login = await post('register', { name: 'Voice Test Candidate', email: `voice-${Date.now()}@example.test`, password: 'test-only-voice-integration-passphrase' });
  assert.equal(login.status, 200);
  const cookie = login.headers.get('set-cookie').split(';')[0];
  const before = await (await fetch(`${base}/api/me`, { headers: { Cookie: cookie } })).json();
  const preferenceUpdate = (language) => fetch(`${base}/api/preferences`, { method: 'PUT', headers: { Cookie: cookie, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...before.preferences, language }) });
  assert.equal((await preferenceUpdate('hi')).status, 200);
  assert.equal((await (await fetch(`${base}/api/me`, { headers: { Cookie: cookie } })).json()).preferences.language, 'hi');
  assert.equal((await preferenceUpdate('invalid')).status, 400);
  const demo = await post('login', { id: 'candidate-demo' });
  assert.equal((await post('voice/challenge', { purpose: 'enroll' }, demo.headers.get('set-cookie').split(';')[0])).status, 403);
  const challenge = await post('voice/challenge', { purpose: 'enroll', user_id: 'admin-demo', language: 'hi' }, cookie);
  assert.equal(challenge.status, 200);
  const data = await challenge.json();
  assert.equal(data.phrases.length, 3);
  assert.equal(data.expires_in, 300);
  assert.equal(data.language, 'hi');
  assert.match(data.phrases[0], /[\u0900-\u097f]/);
  const form = new FormData();
  form.set('challenge_id', data.challenge_id); form.set('consent', 'false');
  for (let i = 0; i < 3; i++) form.append('files', new Blob(['test'], { type: 'audio/webm' }), 'test.webm');
  assert.equal((await fetch(`${base}/api/voice/enroll`, { method: 'POST', headers: { Cookie: cookie }, body: form })).status, 422);
  const admin = await post('login', { id: 'admin-demo' });
  const adminCookie = admin.headers.get('set-cookie').split(';')[0];
  assert.equal((await post('voice/challenge', { purpose: 'enroll' }, adminCookie)).status, 401);
  assert.equal((await post('voice/challenge', { purpose: 'login', identifier: 'candidate-demo' })).status, 200);
  const crossSite = await fetch(`${base}/api/voice/challenge`, { method: 'POST', headers: { Origin: 'https://foreign.example', 'Content-Type': 'application/json', Cookie: cookie }, body: JSON.stringify({ purpose: 'enroll' }) });
  assert.equal(crossSite.status, 403);
  const invalid = new FormData(); invalid.append('file', new Blob(['not audio'], { type: 'text/plain' }), 'bad.txt');
  assert.equal((await fetch(`${base}/api/voice/transcribe`, { method: 'POST', headers: { Cookie: cookie }, body: invalid })).status, 415);
  const available = await (await fetch(`${base}/api/exams`, { headers: { Cookie: cookie } })).json();
  const started = await post('attempts', { examId: available.find(exam => exam.kind === 'practice').id }, cookie);
  assert.equal(started.status, 200);
  const attempt = await started.json();
  const timing = `attempts/${attempt.id}/time`;
  assert.equal((await post(timing, { questionId: attempt.questions[0].id, seconds: -1 }, cookie)).status, 400);
  assert.equal((await post(timing, { questionId: 'unknown', seconds: 1 }, cookie)).status, 400);
  assert.equal((await post(timing, { questionId: attempt.questions[0].id, seconds: 15 }, cookie)).status, 200);
  const saved = await (await fetch(`${base}/api/attempts/${attempt.id}`, { headers: { Cookie: cookie } })).json();
  assert.ok(saved.questionSeconds[attempt.questions[0].id] >= 0);
  assert.ok(saved.questionSeconds[attempt.questions[0].id] <= (Date.now() - saved.startedAt) / 1000);
  assert.equal((await post(timing, { questionId: attempt.questions[0].id, seconds: 1 }, adminCookie)).status, 403);
  await post(`attempts/${attempt.id}/submit`, {}, cookie);
  assert.equal((await (await post(timing, { questionId: attempt.questions[0].id, seconds: 1 }, cookie)).json()).closed, true);
});
